LN/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ItemsController;
use App\Http\Controllers\DashboardController;



/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');     //landing
});

//auth for admin and user
Route::group(['middleware'=> ['auth']],function(){
    route::get('/dashboard','App\Http\Controllers\DashboardController@index')->name('dashboard');
});     //dashboard


//for user
Route::group(['middleware'=> ['auth','role:user']],function(){
    route::get('/dashboard/myprofile','App\Http\Controllers\DashboardController@myprofile')->name('dashboard.myprofile');
    //user profile

});

//for adminn
Route::group(['middleware'=> ['auth','role:admin']],function(){
    route::get('/dashboard/Shop','App\Http\Controllers\DashboardController@shop')->name('dashboard.shop');
    //view sales records
});

Route::resource('items', 'App\Http\Controllers\ItemsController');

Route::get('/buy/{id}', 'App\Http\Controllers\PaymentController@buy')->name('buy');

require __DIR__.'/auth.php';

LN/app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

LN/resources/views/shop/create.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight style="background-color: #58535396"">
            {{ __('Store') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                 
                    

                        <nav class="navbar navbar-inverse">
                         
                            <ul class="nav navbar-nav">
                                <li><a href="{{ URL::to('items') }}" class="p-2 bg-red-100 rounded">View All items</a></li>
                            </ul>
                        </nav>
                        

                        <div>
                            <div class="h-screen flex justify-center items-center">
                              <div class="p-5 bg-gray-400 w-3/4 rounded-lg">
                                
                                <form action="{{ route('items.store') }}" method="POST" enctype="multipart/form-data" class="p-3 flex flex-col space-y-5" >
                             
                                    @csrf
                                    
                                <p class="text-x4">Create New</p>
                                  <input type="text"    name="name"     placeholder="Name" class="p-2 w-3/4bg-gray-100" />
                                  <input type="text"    name="author"   placeholder="Author" class="p-2 bg-gray-100" />
                                  <input type="text"    name="genre"    placeholder="Genre" class="p-2 bg-gray-100" />
                                  <input type="number"  name="cost"   placeholder="Cost" class="p-2 bg-gray-100" />
                                  <input type="number"  name="price"  placeholder="Price"  class="p-2 bg-gray-100" />
                                  <input type="number"  name="stock" placeholder="Stock" class="p-2 bg-gray-100" />
                                  <textarea name="synopsis" placeholder="Synopsis" class="resize-y border rounded-md"> </textarea>
                                  
                                  <input type="file" name="pic" class="p-2 bg-gray-100" />

                                  <button type="submit" class="p-2 bg-gray-100 rounded">submit</button>
                                </form>
                              </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        
    </div>



    
</x-app-layout>

LN/resources/views/shop/edit.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Edit items') }}
            <a href="{{ URL::to('items') }}" ><h3>View All Items</h3></a>
        </h2>
    </x-slot>
 
    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
               
                        
                        <form action="{!! route('items.update', $item->id) !!}" method="POST" 
                          enctype="multipart/form-data" class="p-3 flex flex-col space-y-5" >

                            @csrf
                            @method('PUT')
                            <h5>{{$item->name}}</h5>
                             
                          <input type="text"    name="name"     value="{{ old('name',$item->name) }}"     class="p-2 w-3/4bg-gray-100" />
                          <input type="text"    name="author"   value="{{ old('author',$item->author) }}"   class="p-2 bg-gray-100" />
                          <input type="text"    name="genre"    value="{{ old('genre',$item->genre )}}"    class="p-2 bg-gray-100" />
                          <input type="number"  name="cost"     value="{{ old('cost',$item->cost) }}"    class="p-2 bg-gray-100" />
                          <input type="number"  name="price"    value="{{ old('price',$item->price )}}"    class="p-2 bg-gray-100" />
                          <input type="number"  name="stock"    value="{{ old('stock',$item->stock)}}"     class="p-2 bg-gray-100" />
                          <textarea             name="synopsis" value="{{ old('synopsis',$item->synopsis)}}" class="resize-y border rounded-md"> 
                        </textarea>
                          
                          <img class=" md:object-scale-down object-scale-down h-48 w-full " 
                            src="{{ asset('pic/'. $item->pic)}}" />
                          <input type="file" name="pic" class="p-2 bg-gray-100" />

                          <button type="submit" class="p-2 bg-gray-100 rounded">Update</button>

                        </form>
                      </div>
                    </div>
                </div> 
                </div>
            </div>
        </div>
    </div>



    
</x-app-layout>

LN/resources/views/shop/show.blade.php
<x-app-layout>
    <x-slot name="header">
      

        <h2 class="font-semibold text-xl text-gray-800 leading-tight " >
            <a href="{{ URL::to('items') }}" > {{ __('Store') }}</a>
        </h2>
        </x-slot>

    <section class="text-gray-700 body-font overflow-hidden bg-white ">
        <div class="container px-5 py-24 mx-auto pt-1" >
          <div class="lg:w-4/5 mx-auto flex flex-wrap">
          {{-- img --}}
            <img alt="ecommerce" class="lg:w-1/2 w-full object-cover object-center rounded border border-gray-200" 
            src="{{ asset('pic/'. $item->pic)}}">
            <div class="lg:w-1/2 w-full lg:pl-10 lg:py-6 mt-6 lg:mt-0">
              <h2 class="text-sm title-font text-gray-500 tracking-widest">{{$item->author}}</h2>
              <h2 class="text-sm title-font text-gray-500 tracking-widest">{{$item->genre}}</h2>
              <h1 class="text-gray-900 text-3xl title-font font-medium mb-1">{{$item->name}}</h1>
              <div class="flex mb-4">
              
                 
               
              </div>
              <p class="leading-relaxed">{{$item->synopsis}}</p>
            @if(Auth::user()->hasRole('admin'))
                    
              <div class="flex mt-6 items-center pb-5 border-b-2 border-gray-200 mb-5">
                <h1 class="text-gray-900 text-3xl title-font font-medium mb-1">Stock: {{$item->stock}}</h1>
              </div>
            @endif
            
           @if(Auth::user()->hasRole('user'))
              <div class="flex mt-6 items-center pb-5 border-b-2 border-gray-200 mb-5">
                <h1 class="text-gray-900 text-3xl title-font font-medium mb-1">Stock: {{$stock}}</h1>
              </div>
            @endif
            @if(Auth::user()->hasRole('admin'))
            <span class="title-font font-medium text-2xl text-gray-900 flex mt-6 items-center ">
              Cost: ${{$item->cost}}</span>
            @endif


              <div class="flex">
                <span class="title-font font-medium text-2xl text-gray-900">Price:${{$item->price}} </span>
      
                {{-- fore=user --}}
                @if (Auth::user()->hasRole('user'))
                
                <button id="payment-button"
                class="flex ml-auto text-white bg-red-500 border-0 py-2 px-6 focus:outline-none hover:bg-red-600 rounded btn-color-red">
                 BUY with khalti</button>
                 
                 <button 
                class="flex ml-auto text-white bg-red-500 border-0 py-2 px-6 focus:outline-none hover:bg-red-600 rounded btn-color-red">
                 <a href="{{ URL::to('buy/' . $item->id) }}">BUY proxy</a></button>
                @endif


                
                {{-- for admin --}}
                {{-- edit and delete --}}
                @if(Auth::user()->hasRole('admin'))
                <a href="{{ URL::to('items/' . $item->id . '/edit') }}" class="bg-blue-500 p-2 text-white hover:shadow-lg text-xs font-thin  flex ml-auto text-white bg-red-500 border-0 py-2 px-6 focus:outline-none hover:bg-red-600 rounded mr-2">
                  <h4>Edit</h4></a>
                 
                 {{ Form::open(array('url' => 'items/' . $item->id, 'class' => 'pull-right')) }}
                 {{ Form::hidden('_method', 'DELETE') }}
                 {{ Form::submit('Delete this item', array('class' => 'flex ml-auto text-white bg-red-500 border-0 py-2 px-6 focus:outline-none hover:bg-red-600 rounded"')) }}
                 {{ Form::close() }}
               @endif

              </div>
            </div>
          </div>
        </div>
      </section>

      {{-- khalti script --}}
      <script>
           let pid = {!! json_encode($item->id) !!};
           let pname = {!! json_encode($item->name) !!};
           let res = "127.0.0.1:8000/items/"+pid;
        
       var config = {
            // replace the publicKey with yours
            "publicKey": "live_public_key_4f87617dle3942209abcac1137f47b50",
            "productIdentity": pid,
            "productName": pname,
            "productUrl": res,
            "paymentPreference": [
                "KHALTI",
                "EBANKING",
                "MOBILE_BANKING",
                ],
            "eventHandler": {
                onSuccess (payload) {
                    // hit merchant api for initiating verfication
                    console.log(payload);
                },
                onError (error) {
                    console.log(error);
                },
                onClose () {
                    console.log('widget is closing');
                }
            }
        };

        var checkout = new KhaltiCheckout(config);
        var btn = document.getElementById("payment-button");
        btn.onclick = function () {
            // minimum transaction amount must be 10, i.e 1000 in paisa.
            checkout.show({amount: 1000});
        }
        
      
    </script>





</x-app-layout>